name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy app
      env:
        TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        APP: ${{ secrets.HEROKU_APP_STAGING }}
      run: git push -f https://heroku:$TOKEN@git.heroku.com/$APP.git HEAD:master
